### Create a new User
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "gianluca@gianluca.com",
    "password": "gianlucaPWD"
}

### Sign in 
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "gianluca@gianluca.com",
    "password": "gianlucaPWD"
}

### Find a particular User by id
GET http://localhost:3000/auth/2

### Find a Users by yours email (QUERY STRING)
GET http://localhost:3000/auth?email=asd@asd.com

### Remove a User by id
DELETE http://localhost:3000/auth/423

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "aabb@aaabbb.com",
    "password": "newPassword"
}

